### ISSUE TITLE
Enhance GitHub Pages build

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/docs#89]
# Feature Request

Move the `docs` folder to a dedicated branch, e.g., `gh-pages` or `docsify`, and build the GitHub Pages from there.

## Which Areas Would Be Affected?

`docs`

## Why Is the Feature Desired?

Simplify the structure of this repo. The `docs` folder does not contain any documentation content and can go into a dedicated build branch.

## Solution Proposal

1. Create branch from current `main`. Remove `docs` folder from `main`.
2. Adapt GitHub pages settings. _(admin required)_
3. Update the GH Action to merge into the build branch:
```yml
# update-submodules.yaml

PULL_REQUEST_BRANCH: "docsify"
```

**Comment by ndr-brt** [comment]
Done in #170
