### ISSUE TITLE
Provide a components overview

### ISSUE THREAD

**Issue by juliapampus** [eclipse-edc/docs#92]
# Feature Request

Add documentation about components and their relations.

## Which Areas Would Be Affected?

root

## Why Is the Feature Desired?

See https://github.com/orgs/eclipse-edc/discussions/61

## Solution Proposal

- Two line description of components
- Diagram to visualize the relations of the components

Link in sidebar at "Getting Started".

**Comment by jimmarino** [comment]
This has finally been done with the new documentation, so I will close it out.
